CREATE TABLE PRODUTO (
CODIGO NUMBER(5) PRIMARY KEY,
DESCRICAO VARCHAR2(70), 
PRECO_COMPRA NUMBER(9,2),
LUCRO NUMBER(5,2),
PRECO_VENDA NUMBER(9,2),
ESTOQUE NUMBER(7,2),
TIPO CHAR(2));

INSERT INTO PRODUTO 
VALUES(1,'Queijo Frescal',20.00,25,0,20,'DR');

INSERT INTO PRODUTO 
VALUES(2,'Detergente',2.99,50,0,90,'LT');

INSERT INTO PRODUTO
VALUES(3,'Arroz Tio João',23.50,15,0,50,'PC');

UPDATE PRODUTO 
SET PRECO_COMPRA =
CASE 
    WHEN TIPO = 'DR' THEN PRECO_COMPRA *1.075 
    WHEN TIPO = 'LT' THEN PRECO_COMPRA *1.093
    WHEN TIPO = 'PC' THEN PRECO_COMPRA *1.093
    
END;

UPDATE PRODUTO 
SET PRECO_VENDA = + PRECO_COMPRAx *(1 + (LUCRO/100));

DELETE FROM PRODUTO
WHERE ESTOQUE = 0;

SELECT * FROM PRODUTO
