SELECT * FROM PROFESSOR; // Mostra Tudo

SELECT NOME,NASCIMENTO FROM PROFESSOR; // Somente o nome e nascimento

SELECT NOME,SALARIO,SALARIO*1.15 "Novo Salário " FROM PROFESSOR; // Mostra o salario aumentado também

SELECT NOME ||' Faz aniversário eno mês de ' || TO_CHAR(NASCIMENTO,'MONTH')
|| 'E no dia ' || TO_CHAR(NASCIMENTO,'DD')
|| 'E no ano' || TO_CHAR(NASCIMENTO,'YYYY')

FROM PROFESSOR; // Exibe uma mensagem e pegando apenas uma informação

SELECT NOME,ROUND((SYSDATE-NASCIMENTO),0)/365 FROM PROFESSOR; // Quantos dias de tem

SELECT NOME,ROUND((SYSDATE-NASCIMENTO),0)/365 FROM PROFESSOR; // Quantos anos tem

SELECT NOME,NASCIMENTO
FROM PROFESSOR
ORDER BY NASCIMENTO; // Ordem da mais velha para a mais nova

SELECT NOME,NASCIMENTO,SALARIO
FROM PROFESSOR
ORDER BY SALARIO DESC; // Ordem do maior para o menor para a mais nova

SELECT DEPTO,CARGO,
COUNT(NOME) QTDE,
SUM(SALARIO) SOMA, 
MAX(SALARIO) MAIOR, 
MIN(SALARIO) MENOR,
ROUND(AVG(SALARIO),2) MEDIA
FROM PROFESSOR
GROUP BY DEPTO,CARGO
ORDER BY DEPTO,CARGO;


SELECT NOME,SALARIO
FROM PROFESSOR
WHERE NOME LIKE '%F'; // Mostrando todas as linhas que terminam com F

SELECT NOME,SALARIO
FROM PROFESSOR 
WHERE SALARIO BETWEEN 100 AND 1222; // Mostrando todas as linhas que tenham o salario nesta faixa.


SELECT CODIGO,DESCRICAO
FROM CARGO
WHERE EXISTS
(SELECT NOME FROM PROFESSOR WHERE CARGO=CARGO.CODIGO); // Algum professor em algum cargo

SELECT NOME,CARGO,SALARIO,
DECODE(CARGO,1,SALARIO*1.10,
2,SALARIO*1.15,
3,SALARIO*1.20,
4,SALARIO*1.40) SIMULADO
FROM PROFESSOR
ORDER BY CARGO; // Aplicando aumento por código de cargo



SELECT DISTINCT * FROM PROFESSOR; // NÃO MOSTRA DADOS DUPLICADOS.

SELECT nome,salario+200 FROM PROFESSOR; // Mostra professores com salario maior que 200.

SELECT nome AS "Nome" FROM PROFESSOR; // Da apelidos nas colunas