cmake_minimum_required(VERSION 4.0)
project(C__)

set(CMAKE_CXX_STANDARD 14)

add_executable(C__
        functions/01.cpp
        functions/02.cpp
        functions/03.cpp
        functions/04.cpp
        functions/celio.07.cpp
        functions/celio01-return.cpp
        functions/celio01.cpp
        functions/celio02.cpp
        functions/celio03.cpp
        functions/celio04.cpp
        functions/celio05.cpp
        functions/celio06.cpp
        functions/exemple.cpp
        functions/return.cpp
        functions/thats.cpp
        functions/um.cpp
        lista/menu-school.cpp
        struct/exemplo.cpp
        struct/lista1dois.cpp
        struct/lista1um.cpp
        struct/lista2cinco.cpp
        struct/lista2cincorefined.cpp
        struct/lista2dois.cpp
        struct/lista2quatro.cpp
        struct/lista2seis.cpp
        struct/lista2sete.cpp
        struct/lista2tres.cpp
        struct/lista2um.cpp
        struct/um.cpp)
