cmake_minimum_required(VERSION 4.0)
project(struct)

set(CMAKE_CXX_STANDARD 14)

add_executable(struct
        exemplo.cpp
        lista1dois.cpp
        lista1um.cpp
        lista2cinco.cpp
        lista2cincorefined.cpp
        lista2dois.cpp
        lista2quatro.cpp
        lista2seis.cpp
        lista2sete.cpp
        lista2tres.cpp
        lista2um.cpp
        um.cpp)
